dbt_bgcflow:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dbt_bgcflow.duckdb'
      threads: 2
      extensions:
        - parquet
      external_root: "/home/bgcflow_admin/data2/bgcflow/data/processed/test/data_warehouse"
